"""04. Real-time Streaming Responses.

This example demonstrates how to stream tokens in real-time as they are
generated by the LLM, enabling interactive and responsive user experiences.

Prerequisites:
    Set `OPENAI_API_KEY` in your `.env` file or environment.

Run:
    python examples/04_streaming_chat.py
"""

import asyncio
import os

from dotenv import load_dotenv
from rich import print as rprint

from createagents import CreateAgent

load_dotenv()


async def main() -> None:
    """Run the streaming chat example."""
    if not os.getenv('OPENAI_API_KEY'):
        rprint(
            '[bold yellow]Warning:[/bold yellow] OPENAI_API_KEY is not set.\n'
            'Please configure OPENAI_API_KEY in your .env file.'
        )
        return

    rprint(
        '[bold cyan]Initializing Agent with Real-Time Streaming (stream=True)...[/bold cyan]\n'
    )

    # Enable streaming via config dict
    agent = CreateAgent(
        provider='openai',
        model='gpt-4o-mini',
        name='StreamingPoet',
        instructions='You are an eloquent and creative writer.',
        config={'stream': True},
    )

    user_prompt = 'Write a short 4-line poem about the elegance of clean code.'
    rprint(f'[bold blue]User:[/bold blue] {user_prompt}\n')
    rprint('[bold green]Agent (streaming in real-time):[/bold green]')

    # Send message and stream the response tokens
    response = await agent.chat(user_prompt)

    # When streaming is enabled, response can be iterated asynchronously
    if isinstance(response, str):
        rprint(response, end='')
    else:
        async for token in response:
            rprint(token, end='')

    rprint('\n\n[dim cyan]--- Stream Finished ---[/dim cyan]')


if __name__ == '__main__':
    asyncio.run(main())
